### ISSUE TITLE
The server endpoint doesn't work

### ISSUE THREAD

**Issue by exarkun** [twisted/txacme#148] opened 2019-01-22 00:41 UTC
It looks like someone documented this (I see it at https://github.com/twisted/txacme/blob/master/docs/using.rst) but the documentation was never published where you'd think to look for it (at https://txacme.readthedocs.io/en/stable/using.html#server-endpoint-string).  The published documentation makes it appear as though the server endpoint works though it has apparently been broken for about a year.  I expect this leads to a bunch of wasted effort on the part of prospective users.

**Comment by glyph** [comment] 2020-02-24 03:17
This is a duplicate of #151 - although that came later, it's a little more informative about what the issue is, so I'm closing this one as the dup.

**Closed by glyph** 2020-02-24 03:17 UTC

**Comment by mithrandi** [comment] 2020-02-26 09:33
Duplicate of #151

**Comment by adiroiban** [comment] 2020-02-28 10:06
As part of the initial ACME-v2 implementation, I would remove support for endpoint.
Since TLS-001 is not available, the only option is HTTP-01 and this needs a separate port.

So maybe, leave this ticket open as a reminder that endpoint should be implemented with support for acme v2.
